language: node_js
node_js:
  - "11"
services:
  - docker
before_script:
  - npm install

script:
  - npm run build
  - npm run test

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
#  - docker build -t fmillone/simple-express-proxy:latest .
#  - docker push fmillone/simple-express-proxy

